sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
  - type: npm
    path: extension/package.json
version:
  fromSource: pom.xml
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: true
  exasolDbVersions:
    - "8.26.0" # "8.29.1"
    - "7.1.29"
excludes:
