sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
build:
  runnerOs: ubuntu-20.04
  freeDiskSpace: true
  exasolDbVersions:
    - "7.1.24"
    - "8.23.1"
excludes:
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_upload_github_release_assets.yml'"
