sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
  - type: npm
    path: extension/package.json
version:
  fromSource: pom.xml
build:
  runnerOs: ubuntu-24.04
  freeDiskSpace: true
  exasolDbVersions:
    - "8.34.0"
    - "7.1.30"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Fix "VM Crashed" error by allowing unprivileged user namespaces
            id: fix-vm-crashed
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
excludes:
