sources:
  - type: maven
    path: pom.xml
    modules:
      - jar_artifact
      - integration_tests
      - udf_coverage
  - type: npm
    path: extension/package.json
    artifacts:
      - dist/kafka-connector-extension.js
version:
  fromSource: pom.xml
build:
  runnerOs: ubuntu-24.04
  freeDiskSpace: true
  exasolDbVersions:
    - "2026.1.0"
    - "2025.1.10"
  workflows:
    - name: ci-build.yml
      stepCustomizations:
        - action: INSERT_AFTER
          job: matrix-build
          stepId: enable-testcontainer-reuse
          content:
            name: Fix "VM Crashed" error by allowing unprivileged user namespaces
            id: fix-vm-crashed
            run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
excludes:
